---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  
    - name: copy elastic.repo to /etc/yum.repos.d
      copy:
        src: elastic.repo
        dest: /etc/yum.repos.d/elastic.repo
        
    - name: install metricbeat
      yum:
        name: metricbeat
        state: latest
        
    - name: copy metricbeat.yml to apache servers
      template:
        src: apachemetricbeat.yml.j2
        dest: /etc/metricbeat/metricbeat.yml
      when: lc_role == 'apache'
      
    - name: copy metricbeat.yml to remaining servers
      template:
        src: othermetricbeat.yml.j2
        dest: /etc/metricbeat/metricbeat.yml
      when: lc_role == 'jcr' OR lc_role == 'nonjcr' OR lc_role == 'openfire' OR lc_role == 'job' OR lc_role == 'noticons' OR lc_role == 'activemq'
      
    - name: start metricbeat (systemd)
      systemd:
        name: metricbeat
        state: started
      when: {{ ansible_distribution_major_version }} == '7'
