---
- name: Create test user
  uri:
    url: "https://darwin.enryoku.tech:9199/_security/role/{{ item | urlencode }}"
    method: POST
    body_format: json
    body:
      cluster:
      - manage_index_templates
      - manage_ingest_pipelines
      - monitor
      - manage_ilm
      - "cluster:monitor/xpack/watcher/watch/get"
      - "cluster:admin/xpack/watcher/watch/put"
      - "cluster:admin/xpack/watcher/watch/delete"
      - "cluster:admin/xpack/monitoring/bulk"
      indices:
      - names: "{{ indices }}"
        privileges:
        - index
        - write
        - create
        - delete
        - create_index
        - manage
        - manage_ilm
    status_code: '200'
    user: "elastic"
    password: "n3tadm1n"
    force_basic_auth: yes
    validate_certs: no
  with_items:
    - 'logstash_testing00'
